### PR TITLE
Use async pokemon requests to prevent IO blocking

### PR DESCRIPTION
**Pull request by patrickchiang**

### CODE REVIEW

**Comment by bettse** [comment]
Sorry for the delay, I got distracted by some javascript.  I've refactored a bit of the decoder, and caused some conflicts with the PR.  Could you rebase?  I really like the idea of having this, and I want you to receive credit for it, instead of me copying the code in a new commit.

**Comment by bettse** [comment]
Awesome!  Just to ask the silly question, is their any relative benefit or tradeoff between requests-futures and [qrequests](https://github.com/kennethreitz/grequests) ?

**Comment by patrickchiang** [comment]
For our purposes, they should be about the same. (Can't speak for performance diff.) The point is that our reqs are no longer stopping execution until it finishes. Fire and forget.

**Comment by bettse** [comment]
👍

**Pull request merged**
